import {
  UtensilsCrossed,
  ShoppingCart,
  Car,
  ShoppingBag,
  ReceiptText,
  Clapperboard,
  HeartPulse,
  Home,
  Plane,
  MoreHorizontal,
  Wallet,
  Gift,
  TrendingUp,
  ArrowLeftRight,
  Circle,
  Coffee,
  Fuel,
  Dumbbell,
  GraduationCap,
  PawPrint,
  Shirt,
  Smartphone,
  Zap,
  Baby,
  Briefcase,
  PiggyBank,
  Landmark,
  CreditCard,
  Banknote,
  type LucideIcon,
} from "lucide-react";

/** Map of stored icon names → real Lucide icons. */
const ICONS: Record<string, LucideIcon> = {
  UtensilsCrossed,
  ShoppingCart,
  Car,
  ShoppingBag,
  ReceiptText,
  Clapperboard,
  HeartPulse,
  Home,
  Plane,
  MoreHorizontal,
  Wallet,
  Gift,
  TrendingUp,
  ArrowLeftRight,
  Circle,
  Coffee,
  Fuel,
  Dumbbell,
  GraduationCap,
  PawPrint,
  Shirt,
  Smartphone,
  Zap,
  Baby,
  Briefcase,
  PiggyBank,
  Landmark,
  CreditCard,
  Banknote,
};

/** Render a real Lucide icon by its stored name (falls back to a dot). */
export function CategoryIcon({
  name,
  size = 24,
  ...props
}: { name: string; size?: number } & React.ComponentProps<LucideIcon>) {
  const Cmp = ICONS[name] ?? Circle;
  return <Cmp size={size} absoluteStrokeWidth strokeWidth={2.25} {...props} />;
}
